config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :flowers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "flowers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flower.rb
class Flower < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :set_flower, only: %i[ show edit update destroy ]

  # GET /flowers or /flowers.json
  def index
    @flowers = Flower.all
  end

  # GET /flowers/1 or /flowers/1.json
  def show
  end

  # GET /flowers/new
  def new
    @flower = Flower.new
  end

  # GET /flowers/1/edit
  def edit
  end

  # POST /flowers or /flowers.json
  def create
    @flower = Flower.new(flower_params)

    respond_to do |format|
      if @flower.save
        format.html { redirect_to flower_url(@flower), notice: "Flower was successfully created." }
        format.json { render :show, status: :created, location: @flower }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flowers/1 or /flowers/1.json
  def update
    respond_to do |format|
      if @flower.update(flower_params)
        format.html { redirect_to flower_url(@flower), notice: "Flower was successfully updated." }
        format.json { render :show, status: :ok, location: @flower }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flowers/1 or /flowers/1.json
  def destroy
    @flower.destroy!

    respond_to do |format|
      format.html { redirect_to flowers_url, notice: "Flower was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flower
      @flower = Flower.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flower_params
      params.require(:flower).permit(:image, :name, :scientific_name, :flower_type, :blooming, :color, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/flowers/_flower.html.erb
<div id="<%= dom_id flower %>">


  <p>
      <img src="<%= flower.image %>" alt="flower image" height="180px">
  </p>

  <p>
    <strong>Name:</strong>
    <%= flower.name %>
  </p>

  <p>
    <strong>Scientific name:</strong>
    <%= flower.scientific_name %>
  </p>

  <p>
    <strong>Flower type:</strong>
    <%= flower.flower_type %>
  </p>

  <p>
    <strong>Blooming:</strong>
    <%= flower.blooming %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= flower.color %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= flower.description %>
  </p>

</div>

<footer>
    <p>Copyright © 2024 - PetalPedia</p>
    <nav>
        <a href="/">Accueil</a>
        <a href="/about">À propos</a>
        <a href="/contact">Nous Contacter</a>
    </nav>
</footer>

app/views/flowers/_form.html.erb
<%= form_with(model: flower) do |form| %>
  <% if flower.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(flower.errors.count, "error") %> prohibited this flower from being saved:</h2>

      <ul>
        <% flower.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_area :image %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :scientific_name, style: "display: block" %>
    <%= form.text_field :scientific_name %>
  </div>

  <div>
    <%= form.label :flower_type, style: "display: block" %>
    <%= form.text_field :flower_type %>
  </div>

  <div>
    <%= form.label :blooming, style: "display: block" %>
    <%= form.text_field :blooming %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flowers/edit.html.erb
<h1>Editing flower</h1>

<%= render "form", flower: @flower %>

<br>

<div>
  <%= link_to "Show this flower", @flower %> |
  <%= link_to "Back to flowers", flowers_path %>
</div>

app/views/flowers/index.html.erb
<p style="color: green"><%= notice %></p>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">

<main>

<h1>PetalPedia</h1>

<div id="flowers">
  <% @flowers.each do |flower| %>
    <div class="card">
      <img src="<%= flower.image %>" class="flower_image" alt="Image de fleur" height="300px">
        <div class="card-body">
          <p class="card-text"><%= flower.name %></p>
          <a><%= link_to "Show this flower", flower %></a>
        </div>
    </div>
  <% end %>
</div>

<%= link_to "New flower", new_flower_path %>

</main>

app/views/flowers/new.html.erb
<h1>New flower</h1>

<%= render "form", flower: @flower %>

<br>

<div>
  <%= link_to "Back to flowers", flowers_path %>
</div>

app/views/flowers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flower %>

<div>
  <%= link_to "Edit this flower", edit_flower_path(@flower) %> |
  <%= link_to "Back to flowers", flowers_path %>

  <%= button_to "Destroy this flower", @flower, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<div class="container-flouid">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">
        <h3>Your Logo</h3>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Member</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">Courses</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Blog</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Event</a>
          </li>

        </ul>
        <form class="">
          <a class="btn btn-outline-primary mr-2" href="#">Login</a>
          <a class="btn btn-outline-success" href="#">Become member</a>
        </form>

      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetalPedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>